require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe StopTimesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # StopTime. As you add validations to StopTime, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StopTimesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all stop_times as @stop_times" do
      stop_time = StopTime.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:stop_times)).to eq([stop_time])
    end
  end

  describe "GET show" do
    it "assigns the requested stop_time as @stop_time" do
      stop_time = StopTime.create! valid_attributes
      get :show, {:id => stop_time.to_param}, valid_session
      expect(assigns(:stop_time)).to eq(stop_time)
    end
  end

  describe "GET new" do
    it "assigns a new stop_time as @stop_time" do
      get :new, {}, valid_session
      expect(assigns(:stop_time)).to be_a_new(StopTime)
    end
  end

  describe "GET edit" do
    it "assigns the requested stop_time as @stop_time" do
      stop_time = StopTime.create! valid_attributes
      get :edit, {:id => stop_time.to_param}, valid_session
      expect(assigns(:stop_time)).to eq(stop_time)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StopTime" do
        expect {
          post :create, {:stop_time => valid_attributes}, valid_session
        }.to change(StopTime, :count).by(1)
      end

      it "assigns a newly created stop_time as @stop_time" do
        post :create, {:stop_time => valid_attributes}, valid_session
        expect(assigns(:stop_time)).to be_a(StopTime)
        expect(assigns(:stop_time)).to be_persisted
      end

      it "redirects to the created stop_time" do
        post :create, {:stop_time => valid_attributes}, valid_session
        expect(response).to redirect_to(StopTime.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved stop_time as @stop_time" do
        post :create, {:stop_time => invalid_attributes}, valid_session
        expect(assigns(:stop_time)).to be_a_new(StopTime)
      end

      it "re-renders the 'new' template" do
        post :create, {:stop_time => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested stop_time" do
        stop_time = StopTime.create! valid_attributes
        put :update, {:id => stop_time.to_param, :stop_time => new_attributes}, valid_session
        stop_time.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested stop_time as @stop_time" do
        stop_time = StopTime.create! valid_attributes
        put :update, {:id => stop_time.to_param, :stop_time => valid_attributes}, valid_session
        expect(assigns(:stop_time)).to eq(stop_time)
      end

      it "redirects to the stop_time" do
        stop_time = StopTime.create! valid_attributes
        put :update, {:id => stop_time.to_param, :stop_time => valid_attributes}, valid_session
        expect(response).to redirect_to(stop_time)
      end
    end

    describe "with invalid params" do
      it "assigns the stop_time as @stop_time" do
        stop_time = StopTime.create! valid_attributes
        put :update, {:id => stop_time.to_param, :stop_time => invalid_attributes}, valid_session
        expect(assigns(:stop_time)).to eq(stop_time)
      end

      it "re-renders the 'edit' template" do
        stop_time = StopTime.create! valid_attributes
        put :update, {:id => stop_time.to_param, :stop_time => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested stop_time" do
      stop_time = StopTime.create! valid_attributes
      expect {
        delete :destroy, {:id => stop_time.to_param}, valid_session
      }.to change(StopTime, :count).by(-1)
    end

    it "redirects to the stop_times list" do
      stop_time = StopTime.create! valid_attributes
      delete :destroy, {:id => stop_time.to_param}, valid_session
      expect(response).to redirect_to(stop_times_url)
    end
  end

end
